version: '3.9'

services:
  bot:
    build: ./src
    container_name: mmo_bot
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    expose:
      - "8000"

  db:
    image: postgres:15
    container_name: mmo_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data

  nginx:
    image: nginx:stable-alpine
    container_name: mmo_nginx
    restart: always
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - bot

  certbot:
    image: certbot/certbot
    container_name: mmo_certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    entrypoint: /bin/sh -c "trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;"

volumes:
  db_data:
