version: '3.8'
services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: mmo
    volumes:
      - pgdata:/var/lib/postgresql/data
  bot:
    build: .
    depends_on:
      - db
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - DATABASE_URL=${DATABASE_URL}
      - ADMIN_IDS=${ADMIN_IDS}
    volumes:
      - ./src:/app/src
    restart: unless-stopped
volumes:
  pgdata:
